print("Cristian Vladimir Fuentes Portillo")
print("Valeria Elizabeth Pacas Portillo")
print("Christopher Alexander Hernandez Ramos")
print("Bismark Alexander Galdamez Penate")
print("Ariana Marissa Guzman Castro")
print("Jose Roberto Siciliano Menjivar")